### ISSUE TITLE
Typo In T1117_regsvr32.xml Rule

### ISSUE THREAD

**Issue by davehardy20** [Cyb3rWard0g/ThreatHunter-Playbook#10]
Hi CyberWard0g,

I found a typo in the T1117_regsvr32.xml rule

Line 7      <Image condition="is">C:\Windows\System\32\regsvr32.exe</Image>

should read

<Image condition="is">C:\Windows\System32\regsvr32.exe</Image>

Superb resources, HELK and ThreatHunter-Playbook, many thanks for sharing

Dave

**Comment by Cyb3rWard0g** [comment]
Thank you very much @davehardy20 !! 👍  I updated it with https://github.com/Cyb3rWard0g/ThreatHunter-Playbook/commit/04f9eb464a271b6a6434d249d7284369f894fe3f . Thank you!
