### ISSUE TITLE
T1185 - Man in the Browser missing from Windows Collection

### ISSUE THREAD

**Issue by PolarBearGod** [Cyb3rWard0g/ThreatHunter-Playbook#24]
Man in the Browser technique is missing from the Windows Collection Tactic column in the map. See link form ore details.

https://attack.mitre.org/wiki/Technique/T1185

**Comment by Cyb3rWard0g** [comment]
thank you @PolarBearGod . I have updated the whole project and the ATT&CK Map is not longer part of the tactics folders.
