### ISSUE TITLE
Typos in atomic Sysmon configs results in a failure to parse

### ISSUE THREAD

**Issue by mattifestation** [Cyb3rWard0g/ThreatHunter-Playbook#6]
There are many ProcessCreate closing tags that have a "]" in them - e.g. T0000_bitsadmin.xml

**Comment by Cyb3rWard0g** [comment]
Fixed with Commit: https://github.com/Cyb3rWard0g/ThreatHunter-Playbook/commit/0f132722b58a601afe90d148b75e1613ef5a3085
